# Generated by Django 4.2 on 2023-05-04 14:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cabinet',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('avail', models.BooleanField(default=True)),
                ('open', models.BooleanField(default=False)),
                ('coord', models.CharField(default='Test coord')),
                ('start', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'cabinet',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('name', models.CharField()),
                ('email', models.CharField(unique=True)),
                ('password', models.CharField()),
                ('photo', models.CharField(blank=True, null=True)),
            ],
            options={
                'db_table': 'customer',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='CabinetLockerRentals',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('rentdate', models.DateTimeField()),
                ('duration', models.DurationField()),
                ('paymentmethod', models.CharField()),
                ('fee', models.DecimalField(decimal_places=0, max_digits=10)),
                ('cabinetid', models.ForeignKey(db_column='cabinetid', on_delete=django.db.models.deletion.DO_NOTHING, to='demo.cabinet')),
                ('customerid', models.ForeignKey(db_column='customerid', on_delete=django.db.models.deletion.DO_NOTHING, to='demo.customer')),
            ],
            options={
                'db_table': 'cabinet_locker_rentals',
                'managed': True,
            },
        ),
        migrations.AddField(
            model_name='cabinet',
            name='userid',
            field=models.ForeignKey(blank=True, db_column='userid', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='demo.customer'),
        ),
    ]
