# Generated by Django 3.2.12 on 2023-05-05 03:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cabinet',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('avail', models.BooleanField(default=True)),
                ('open', models.BooleanField(default=False)),
                ('coord', models.CharField(default='Test coord', max_length=100)),
                ('start', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'cabinet',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='CabinetLockerRentals',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('rentdate', models.DateTimeField()),
                ('duration', models.DurationField()),
                ('paymentmethod', models.CharField(max_length=100)),
                ('fee', models.DecimalField(decimal_places=0, max_digits=10)),
            ],
            options={
                'db_table': 'cabinet_locker_rentals',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('email', models.CharField(max_length=100, unique=True)),
                ('password', models.CharField(max_length=100)),
                ('photo', models.CharField(blank=True, max_length=100, null=True)),
            ],
            options={
                'db_table': 'customer',
                'managed': False,
            },
        ),
    ]
