# Generated by Django 3.2.12 on 2023-04-18 09:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('demo', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customer',
            name='credentials',
        ),
        migrations.AddField(
            model_name='customer',
            name='email',
            field=models.CharField(default='nvkhoan@hcmutc.com', max_length=40),
        ),
        migrations.AddField(
            model_name='customer',
            name='image',
            field=models.CharField(default='/images/whatever', max_length=40),
        ),
        migrations.AddField(
            model_name='customer',
            name='password',
            field=models.CharField(blank=True, default=123456, max_length=30, null=True),
        ),
    ]
