# Generated by Django 3.2.12 on 2023-04-27 14:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('demo', '0002_auto_20230418_0936'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cabinetlockerrentals',
            name='id',
            field=models.BigAutoField(primary_key=True, serialize=False),
        ),
    ]
