// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.17.0

package db

import (
	"database/sql"
	"time"
)

type Cabinet struct {
	ID     int64         `json:"id"`
	Avail  bool          `json:"avail"`
	Open   bool          `json:"open"`
	Coord  string        `json:"coord"`
	Start  sql.NullTime  `json:"start"`
	Userid sql.NullInt64 `json:"userid"`
}

type CabinetLockerRental struct {
	ID            int64     `json:"id"`
	Cabinetid     int64     `json:"cabinetid"`
	Customerid    int64     `json:"customerid"`
	Rentdate      time.Time `json:"rentdate"`
	Duration      string    `json:"duration"`
	Paymentmethod string    `json:"paymentmethod"`
	Fee           float64   `json:"fee"`
}

type Customer struct {
	ID       int64          `json:"id"`
	Name     string         `json:"name"`
	Email    string         `json:"email"`
	Password string         `json:"password"`
	Photo    sql.NullString `json:"photo"`
}
