// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.17.0

package db

import (
	"context"
	"database/sql"
)

type Querier interface {
	CreateCabinetRental(ctx context.Context, arg CreateCabinetRentalParams) (CabinetLockerRental, error)
	CreateCustomer(ctx context.Context, arg CreateCustomerParams) (Customer, error)
	GetAvailableCabinet(ctx context.Context) ([]Cabinet, error)
	GetCabinetByID(ctx context.Context, id int64) (Cabinet, error)
	GetCabinetForRent(ctx context.Context, id int64) (Cabinet, error)
	GetCustomer(ctx context.Context, id int64) (Customer, error)
	GetCustomerByEmail(ctx context.Context, email string) (Customer, error)
	GetUserCabinet(ctx context.Context, userid sql.NullInt64) ([]Cabinet, error)
	RentCabinet(ctx context.Context, arg RentCabinetParams) error
	UnrentCabinet(ctx context.Context, id int64) error
	UpdateCabinetClose(ctx context.Context, id int64) (Cabinet, error)
	UpdateCabinetOpen(ctx context.Context, id int64) (Cabinet, error)
	UpdateUserPhoto(ctx context.Context, arg UpdateUserPhotoParams) error
}

var _ Querier = (*Queries)(nil)
